<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
 | This file reads from your .env configuration file and should not
 | be modified directly.
*/

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Stripe, Mailgun, Mandrill, and others. This file provides a sane
    | default location for this type of information, allowing packages
    | to have a conventional place to find your various credentials.
    |
    */

    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
        'endpoint' => env('MAILGUN_ENDPOINT', 'api.mailgun.net'),
    ],

    'mandrill' => [
        'secret' => env('MANDRILL_SECRET'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'stripe' => [
        'model'  => App\User::class,
        'key'    => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
    ],

    'google' => [
        'maps_api_key' => env('GOOGLE_MAPS_API'),
    ],

    'ollama' => [
        'enabled' => env('OLLAMA_ENABLED', false),
        'base_url' => env('OLLAMA_BASE_URL', 'http://127.0.0.1:11434'),
        'api_key' => env('OLLAMA_API_KEY'),
        'auth_header' => env('OLLAMA_AUTH_HEADER', 'Authorization'),
        'auth_scheme' => env('OLLAMA_AUTH_SCHEME', 'Bearer'),
        'model' => env('OLLAMA_MODEL', 'llama3.2:latest'),
        'timeout' => env('OLLAMA_TIMEOUT', 45),
    ],

    'firebase' => [
        'project_id' => env('FIREBASE_PROJECT_ID'),
        'database' => env('FIREBASE_DATABASE', '(default)'),
        'helpdesk_collection' => env('FIREBASE_HELPDESK_COLLECTION', 'helpdesk_tickets'),
        'service_account_json' => env('FIREBASE_SERVICE_ACCOUNT_JSON'),
        'service_account_path' => env('FIREBASE_SERVICE_ACCOUNT_PATH'),
        'token_uri' => env('FIREBASE_TOKEN_URI', 'https://oauth2.googleapis.com/token'),
        'firestore_base_url' => env('FIREBASE_FIRESTORE_BASE_URL', 'https://firestore.googleapis.com/v1'),
    ],

    'jira' => [
        'base_url' => env('JIRA_BASE_URL'),
        'email' => env('JIRA_EMAIL'),
        'api_token' => env('JIRA_API_TOKEN'),
        'project_key' => env('JIRA_PROJECT_KEY'),
        'timeout' => env('JIRA_TIMEOUT', 30),
        'issue_types' => [
            'Task' => env('JIRA_ISSUE_TYPE_TASK', 'Task'),
            'Bug' => env('JIRA_ISSUE_TYPE_BUG', 'Bug'),
            'Incident' => env('JIRA_ISSUE_TYPE_INCIDENT', 'Incident'),
            'Service Request' => env('JIRA_ISSUE_TYPE_SERVICE_REQUEST', 'Service Request'),
        ],
    ],

];
